//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardrobeItem
    {
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public int ColorID { get; set; }
        public int SeasonID { get; set; }
        public int TypeID { get; set; }
        public int OcassionID { get; set; }
    
        public virtual ItemColor ItemColor { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Ocassion Ocassion { get; set; }
        public virtual Season Season { get; set; }
    }
}
